openapi: '3.0.3'
info:
  title: Software Template
  version: 'v1alpha1'
components:
  schemas:
    ParameterInput:
      type: object
      properties:
        name: 
          type: string
        ui:field:
          type: string
          enum:
            - Dropdown
            - Input
        ui:otions:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
              value:
                type: string
      required:
        - name
        - ui:field
        
    Parameters:
      type: object
      properties:
        title:
          type: string
        parameters:
          type: array
          oneOf:
            - $ref: '#/components/schemas/ParameterInput'

    TemplatingTemplate:
      type: object
      properties:
        apiVersion:
          type: string
          example: templating.catcode.mw/v1alpha1
        kind:
          type: string
          example: Template
        metadata:
          type: object
          properties:
            name: 
              type: string
              example: PythonCronjob
            title:
              type: string
              example: Python Cronjob Template
            descrition:
              type: string
              example: Python job template
        spec:
          type: object
          properties:
            owner:
              type: string
            type:
              type: string
              example: Service
            parameters:
              type: array
              items:
                oneOf:
                  - $ref: '#/components/schemas/Parameters'
                
    
